"""Initial migration.

Revision ID: 8ca2bd54f84d
Revises: 
Create Date: 2021-01-06 15:13:54.651393

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ca2bd54f84d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_details')
    op.drop_table('transaction_headers')
    op.drop_table('wallets')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_token', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='categories_pkey')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('token', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('token_expiration', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_users_token', 'users', ['token'], unique=True)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('transaction_details',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('added_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id_header', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('id_wallet', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_header'], ['transaction_headers.id'], name='transaction_details_id_header_fkey'),
    sa.ForeignKeyConstraint(['id_wallet'], ['wallets.id'], name='transaction_details_id_wallet_fkey'),
    sa.PrimaryKeyConstraint('id', name='transaction_details_pkey')
    )
    op.create_table('wallets',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('initial_value', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('default_currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='wallets_pkey')
    )
    op.create_table('transaction_headers',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('added_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='transaction_headers_pkey')
    )
    # ### end Alembic commands ###
